// =========================================================================
//                             api.pb.c
// =========================================================================
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HelloRequest, HelloRequest, AUTO)


PB_BIND(HelloResponse, HelloResponse, AUTO)